"""
Android AAP - Android Audio Plugin stub for iDAW.

Generates Kotlin/Java scaffolding for Android Audio Plugins (AAP).
AAP is the emerging standard for audio plugins on Android.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any


@dataclass
class AndroidAAPConfig:
    """Configuration for Android Audio Plugin."""
    name: str = "iDAW"
    package_name: str = "com.idaw.plugin"
    version: str = "1.0.0"
    version_code: int = 1

    # Plugin type
    is_instrument: bool = True  # False for effect
    is_midi_effect: bool = False

    # Audio configuration
    sample_rates: List[int] = field(default_factory=lambda: [44100, 48000])
    channel_configs: List[tuple] = field(default_factory=lambda: [(2, 2)])

    # MIDI support
    midi_input: bool = True
    midi_output: bool = False

    # UI
    has_ui: bool = True
    ui_activity: str = "PluginActivity"

    # Build configuration
    min_sdk: int = 29  # Android 10
    target_sdk: int = 34  # Android 14
    ndk_version: str = "25.2.9519653"


def generate_android_plugin_stub(config: AndroidAAPConfig) -> Dict[str, str]:
    """
    Generate Android Audio Plugin scaffolding.

    Args:
        config: AAP configuration

    Returns:
        Dict mapping file paths to content
    """
    files = {}

    # Gradle files
    files["build.gradle.kts"] = generate_build_gradle(config)
    files["settings.gradle.kts"] = generate_settings_gradle(config)

    # Android manifest
    files["src/main/AndroidManifest.xml"] = generate_manifest(config)

    # AAP metadata
    files["src/main/res/xml/aap_metadata.xml"] = generate_aap_metadata(config)

    # Kotlin source
    files[f"src/main/kotlin/{config.package_name.replace('.', '/')}/PluginService.kt"] = \
        generate_plugin_service(config)
    files[f"src/main/kotlin/{config.package_name.replace('.', '/')}/PluginProcessor.kt"] = \
        generate_plugin_processor(config)

    # Native code
    files["src/main/cpp/CMakeLists.txt"] = generate_cmake(config)
    files["src/main/cpp/native-lib.cpp"] = generate_native_lib(config)
    files["src/main/cpp/dsp_kernel.hpp"] = generate_dsp_kernel(config)
    files["src/main/cpp/dsp_kernel.cpp"] = generate_dsp_kernel_cpp(config)

    return files


def generate_build_gradle(config: AndroidAAPConfig) -> str:
    """Generate build.gradle.kts."""
    return f'''// build.gradle.kts
// Generated by iDAW Mobile Module

plugins {{
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}}

android {{
    namespace = "{config.package_name}"
    compileSdk = {config.target_sdk}

    defaultConfig {{
        applicationId = "{config.package_name}"
        minSdk = {config.min_sdk}
        targetSdk = {config.target_sdk}
        versionCode = {config.version_code}
        versionName = "{config.version}"

        externalNativeBuild {{
            cmake {{
                cppFlags += "-std=c++17"
                arguments += "-DANDROID_STL=c++_shared"
            }}
        }}
    }}

    buildTypes {{
        release {{
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }}
    }}

    externalNativeBuild {{
        cmake {{
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.22.1"
        }}
    }}

    compileOptions {{
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }}

    kotlinOptions {{
        jvmTarget = "17"
    }}

    ndkVersion = "{config.ndk_version}"
}}

dependencies {{
    implementation("org.androidaudioplugin:androidaudioplugin:0.7.8")
    implementation("org.androidaudioplugin:androidaudioplugin-ui-compose:0.7.8")
    implementation("androidx.core:core-ktx:1.12.0")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("com.google.android.material:material:1.11.0")
    implementation("androidx.compose.ui:ui:1.5.4")
    implementation("androidx.compose.material3:material3:1.1.2")
}}
'''


def generate_settings_gradle(config: AndroidAAPConfig) -> str:
    """Generate settings.gradle.kts."""
    return f'''// settings.gradle.kts
// Generated by iDAW Mobile Module

pluginManagement {{
    repositories {{
        google()
        mavenCentral()
        gradlePluginPortal()
    }}
}}

dependencyResolutionManagement {{
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {{
        google()
        mavenCentral()
        maven {{ url = uri("https://jitpack.io") }}
    }}
}}

rootProject.name = "{config.name}"
include(":app")
'''


def generate_manifest(config: AndroidAAPConfig) -> str:
    """Generate AndroidManifest.xml."""
    return f'''<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-feature android:name="android.software.midi" android:required="false" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/Theme.iDAW">

        <!-- AAP Service -->
        <service
            android:name=".PluginService"
            android:exported="true"
            android:label="{config.name}">
            <intent-filter>
                <action android:name="org.androidaudioplugin.AudioPluginService" />
            </intent-filter>
            <meta-data
                android:name="org.androidaudioplugin.AudioPluginService#Plugins"
                android:resource="@xml/aap_metadata" />
        </service>

        {"" if not config.has_ui else f'''
        <activity
            android:name=".{config.ui_activity}"
            android:exported="true"
            android:theme="@style/Theme.iDAW">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        '''}

    </application>

</manifest>
'''


def generate_aap_metadata(config: AndroidAAPConfig) -> str:
    """Generate AAP metadata XML."""
    plugin_type = "Instrument" if config.is_instrument else "Effect"

    return f'''<?xml version="1.0" encoding="utf-8"?>
<plugins xmlns="urn:org.androidaudioplugin.core"
         xmlns:pp="urn:org.androidaudioplugin.port">

    <plugin
        name="{config.name}"
        category="{plugin_type}"
        author="iDAW Team"
        manufacturer="iDAW"
        unique-id="idaw.{config.name.lower()}"
        version="{config.version}"
        library="lib{config.name.lower()}.so"
        entrypoint="GetPluginFactory">

        <ports>
            <!-- Audio Ports -->
            <port direction="input" content="audio" name="Left In" />
            <port direction="input" content="audio" name="Right In" />
            <port direction="output" content="audio" name="Left Out" />
            <port direction="output" content="audio" name="Right Out" />

            {"<!-- MIDI Input -->" if config.midi_input else ""}
            {"<port direction='input' content='midi2' name='MIDI In' />" if config.midi_input else ""}

            {"<!-- MIDI Output -->" if config.midi_output else ""}
            {"<port direction='output' content='midi2' name='MIDI Out' />" if config.midi_output else ""}

            <!-- Parameters -->
            <port direction="input" content="other" name="Volume"
                  pp:default="1.0" pp:minimum="0.0" pp:maximum="1.0" />
            <port direction="input" content="other" name="Pan"
                  pp:default="0.0" pp:minimum="-1.0" pp:maximum="1.0" />
            <port direction="input" content="other" name="Mix"
                  pp:default="1.0" pp:minimum="0.0" pp:maximum="1.0" />
        </ports>

    </plugin>

</plugins>
'''


def generate_plugin_service(config: AndroidAAPConfig) -> str:
    """Generate Kotlin plugin service."""
    return f'''// PluginService.kt
// Generated by iDAW Mobile Module

package {config.package_name}

import org.androidaudioplugin.AudioPluginService

class PluginService : AudioPluginService() {{

    companion object {{
        init {{
            System.loadLibrary("{config.name.lower()}")
        }}
    }}
}}
'''


def generate_plugin_processor(config: AndroidAAPConfig) -> str:
    """Generate Kotlin plugin processor."""
    return f'''// PluginProcessor.kt
// Generated by iDAW Mobile Module

package {config.package_name}

import org.androidaudioplugin.*

class PluginProcessor(private val pluginId: String) {{

    private var sampleRate: Float = 48000f
    private var bufferSize: Int = 512

    external fun nativeProcess(
        inputL: FloatArray,
        inputR: FloatArray,
        outputL: FloatArray,
        outputR: FloatArray,
        frameCount: Int
    )

    {"external fun nativeHandleMidi(data: ByteArray, length: Int)" if config.midi_input else ""}

    external fun nativeSetParameter(address: Int, value: Float)
    external fun nativeGetParameter(address: Int): Float

    fun configure(sampleRate: Float, bufferSize: Int) {{
        this.sampleRate = sampleRate
        this.bufferSize = bufferSize
    }}

    fun process(
        inputBuffers: Array<FloatArray>,
        outputBuffers: Array<FloatArray>,
        frameCount: Int
    ) {{
        if (inputBuffers.size >= 2 && outputBuffers.size >= 2) {{
            nativeProcess(
                inputBuffers[0],
                inputBuffers[1],
                outputBuffers[0],
                outputBuffers[1],
                frameCount
            )
        }}
    }}

    companion object {{
        init {{
            System.loadLibrary("{config.name.lower()}")
        }}
    }}
}}
'''


def generate_cmake(config: AndroidAAPConfig) -> str:
    """Generate CMakeLists.txt for native code."""
    return f'''# CMakeLists.txt
# Generated by iDAW Mobile Module

cmake_minimum_required(VERSION 3.22.1)
project("{config.name.lower()}")

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Find Oboe for low-latency audio
find_package(oboe REQUIRED CONFIG)

# Source files
add_library(
    {config.name.lower()}
    SHARED

    native-lib.cpp
    dsp_kernel.cpp
)

# Link libraries
target_link_libraries(
    {config.name.lower()}

    android
    log
    oboe::oboe
)

# Include directories
target_include_directories(
    {config.name.lower()}
    PRIVATE

    ${{CMAKE_CURRENT_SOURCE_DIR}}
)
'''


def generate_native_lib(config: AndroidAAPConfig) -> str:
    """Generate native JNI library."""
    return f'''// native-lib.cpp
// Generated by iDAW Mobile Module

#include <jni.h>
#include <android/log.h>
#include "dsp_kernel.hpp"

#define LOG_TAG "{config.name}"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

static {config.name}DSPKernel g_kernel;

extern "C" {{

JNIEXPORT void JNICALL
Java_{config.package_name.replace('.', '_')}_PluginProcessor_nativeProcess(
    JNIEnv* env,
    jobject /* this */,
    jfloatArray inputL,
    jfloatArray inputR,
    jfloatArray outputL,
    jfloatArray outputR,
    jint frameCount) {{

    jfloat* inL = env->GetFloatArrayElements(inputL, nullptr);
    jfloat* inR = env->GetFloatArrayElements(inputR, nullptr);
    jfloat* outL = env->GetFloatArrayElements(outputL, nullptr);
    jfloat* outR = env->GetFloatArrayElements(outputR, nullptr);

    g_kernel.process(inL, inR, outL, outR, frameCount);

    env->ReleaseFloatArrayElements(inputL, inL, 0);
    env->ReleaseFloatArrayElements(inputR, inR, 0);
    env->ReleaseFloatArrayElements(outputL, outL, 0);
    env->ReleaseFloatArrayElements(outputR, outR, 0);
}}

{"JNIEXPORT void JNICALL" if config.midi_input else ""}
{"Java_" + config.package_name.replace('.', '_') + "_PluginProcessor_nativeHandleMidi(" if config.midi_input else ""}
{"    JNIEnv* env," if config.midi_input else ""}
{"    jobject /* this */," if config.midi_input else ""}
{"    jbyteArray data," if config.midi_input else ""}
{"    jint length) {{" if config.midi_input else ""}
{"" if config.midi_input else ""}
{"    jbyte* bytes = env->GetByteArrayElements(data, nullptr);" if config.midi_input else ""}
{"    g_kernel.handleMidi(reinterpret_cast<uint8_t*>(bytes), length);" if config.midi_input else ""}
{"    env->ReleaseByteArrayElements(data, bytes, 0);" if config.midi_input else ""}
{"}}" if config.midi_input else ""}

JNIEXPORT void JNICALL
Java_{config.package_name.replace('.', '_')}_PluginProcessor_nativeSetParameter(
    JNIEnv* env,
    jobject /* this */,
    jint address,
    jfloat value) {{

    g_kernel.setParameter(address, value);
}}

JNIEXPORT jfloat JNICALL
Java_{config.package_name.replace('.', '_')}_PluginProcessor_nativeGetParameter(
    JNIEnv* env,
    jobject /* this */,
    jint address) {{

    return g_kernel.getParameter(address);
}}

}} // extern "C"
'''


def generate_dsp_kernel(config: AndroidAAPConfig) -> str:
    """Generate DSP kernel header."""
    return f'''// dsp_kernel.hpp
// Generated by iDAW Mobile Module

#pragma once

#include <cstdint>
#include <algorithm>
#include <vector>

class {config.name}DSPKernel {{
public:
    {config.name}DSPKernel();
    ~{config.name}DSPKernel();

    void setSampleRate(float sampleRate);
    void setBufferSize(int bufferSize);

    void process(float* inL, float* inR,
                 float* outL, float* outR,
                 int frameCount);

    {"void handleMidi(const uint8_t* data, int length);" if config.midi_input else ""}

    void setParameter(int address, float value);
    float getParameter(int address);

private:
    float sampleRate_ = 48000.0f;
    int bufferSize_ = 512;

    // Parameters
    float volume_ = 1.0f;
    float pan_ = 0.0f;
    float mix_ = 1.0f;
}};
'''


def generate_dsp_kernel_cpp(config: AndroidAAPConfig) -> str:
    """Generate DSP kernel implementation."""
    return f'''// dsp_kernel.cpp
// Generated by iDAW Mobile Module

#include "dsp_kernel.hpp"
#include <cmath>

{config.name}DSPKernel::{config.name}DSPKernel() {{
}}

{config.name}DSPKernel::~{config.name}DSPKernel() {{
}}

void {config.name}DSPKernel::setSampleRate(float sampleRate) {{
    sampleRate_ = sampleRate;
}}

void {config.name}DSPKernel::setBufferSize(int bufferSize) {{
    bufferSize_ = bufferSize;
}}

void {config.name}DSPKernel::process(float* inL, float* inR,
                                      float* outL, float* outR,
                                      int frameCount) {{
    // Simple pass-through with volume and pan
    float leftGain = volume_ * (1.0f - std::max(0.0f, pan_));
    float rightGain = volume_ * (1.0f + std::min(0.0f, pan_));

    for (int i = 0; i < frameCount; ++i) {{
        outL[i] = inL[i] * leftGain * mix_ + inL[i] * (1.0f - mix_);
        outR[i] = inR[i] * rightGain * mix_ + inR[i] * (1.0f - mix_);
    }}
}}

{"void " + config.name + "DSPKernel::handleMidi(const uint8_t* data, int length) {{" if config.midi_input else ""}
{"    if (length < 1) return;" if config.midi_input else ""}
{"" if config.midi_input else ""}
{"    uint8_t status = data[0] & 0xF0;" if config.midi_input else ""}
{"    // uint8_t channel = data[0] & 0x0F;" if config.midi_input else ""}
{"" if config.midi_input else ""}
{"    switch (status) {{" if config.midi_input else ""}
{"        case 0x90: // Note On" if config.midi_input else ""}
{"            if (length >= 3) {{" if config.midi_input else ""}
{"                // Handle note on" if config.midi_input else ""}
{"            }}" if config.midi_input else ""}
{"            break;" if config.midi_input else ""}
{"        case 0x80: // Note Off" if config.midi_input else ""}
{"            if (length >= 3) {{" if config.midi_input else ""}
{"                // Handle note off" if config.midi_input else ""}
{"            }}" if config.midi_input else ""}
{"            break;" if config.midi_input else ""}
{"        case 0xB0: // Control Change" if config.midi_input else ""}
{"            if (length >= 3) {{" if config.midi_input else ""}
{"                // Handle CC" if config.midi_input else ""}
{"            }}" if config.midi_input else ""}
{"            break;" if config.midi_input else ""}
{"    }}" if config.midi_input else ""}
{"}}" if config.midi_input else ""}

void {config.name}DSPKernel::setParameter(int address, float value) {{
    switch (address) {{
        case 0: volume_ = value; break;
        case 1: pan_ = value; break;
        case 2: mix_ = value; break;
    }}
}}

float {config.name}DSPKernel::getParameter(int address) {{
    switch (address) {{
        case 0: return volume_;
        case 1: return pan_;
        case 2: return mix_;
        default: return 0.0f;
    }}
}}
'''


def get_android_requirements() -> Dict[str, Any]:
    """
    Get Android AAP development requirements.

    Returns:
        Dict with requirements and resources
    """
    return {
        "android_studio_version": "Hedgehog (2023.1.1)+",
        "kotlin_version": "1.9.0+",
        "android_minimum": "Android 10 (API 29)",
        "android_target": "Android 14 (API 34)",
        "ndk_version": "25.2.9519653",
        "cmake_version": "3.22.1",
        "dependencies": [
            "org.androidaudioplugin:androidaudioplugin:0.7.8",
            "Google Oboe (low-latency audio)",
        ],
        "build_tools": [
            "Gradle 8.0+",
            "Android NDK",
            "CMake",
        ],
        "testing_apps": [
            "AAP Host (from AAP repository)",
            "AudioPluginHost (native)",
        ],
        "distribution": [
            "Google Play Store",
            "F-Droid (FOSS)",
            "Direct APK",
        ],
        "resources": [
            "https://github.com/atsushieno/aap-core",
            "https://github.com/google/oboe",
            "https://developer.android.com/ndk",
        ],
        "notes": [
            "AAP is still evolving - API may change",
            "Limited host support compared to desktop plugins",
            "Consider bundling with standalone app",
        ],
    }
