# music_brain/effects/__init__.py
"""
DAiW Guitar Effects Engine - The Most Customizable Effects Modulator

Every effect. Every technique. Fully modular. Emotionally aware.
"""

from music_brain.effects.guitar_fx import (
    GuitarFXEngine,
    EffectChain,
    EffectPreset,
    ModulationMatrix,
    SignalRouter,
    create_preset_from_emotion,
    get_effect_suggestions,
    EFFECT_CATEGORIES,
    ALL_EFFECTS,
)

from music_brain.effects.effects import (
    DistortionEffect,
    OverdriveEffect,
    FuzzEffect,
    ChorusEffect,
    FlangerEffect,
    PhaserEffect,
    TremoloEffect,
    VibratoEffect,
    RotaryEffect,
    RingModEffect,
    UnivibeEffect,
    DelayEffect,
    ReverbEffect,
    CompressorEffect,
    NoiseGateEffect,
    EQEffect,
    WahEffect,
    PitchShiftEffect,
    HarmonizerEffect,
    OctaverEffect,
    AmpSimEffect,
    CabinetSimEffect,
    LooperEffect,
    GranularEffect,
    ShimmerEffect,
    FreezeEffect,
    SlicerEffect,
    FilterEffect,
    BitcrusherEffect,
)

from music_brain.effects.base import (
    LFOSource,
    EnvelopeFollower,
    StepSequencer,
    RandomSource,
    ExpressionInput,
    MIDISource,
    EmotionSource,
)

__all__ = [
    "GuitarFXEngine",
    "EffectChain",
    "EffectPreset",
    "ModulationMatrix",
    "SignalRouter",
    "DistortionEffect",
    "OverdriveEffect",
    "FuzzEffect",
    "ChorusEffect",
    "FlangerEffect",
    "PhaserEffect",
    "TremoloEffect",
    "VibratoEffect",
    "RotaryEffect",
    "RingModEffect",
    "UnivibeEffect",
    "DelayEffect",
    "ReverbEffect",
    "CompressorEffect",
    "NoiseGateEffect",
    "EQEffect",
    "WahEffect",
    "PitchShiftEffect",
    "HarmonizerEffect",
    "OctaverEffect",
    "AmpSimEffect",
    "CabinetSimEffect",
    "LooperEffect",
    "GranularEffect",
    "ShimmerEffect",
    "FreezeEffect",
    "SlicerEffect",
    "FilterEffect",
    "BitcrusherEffect",
    "LFOSource",
    "EnvelopeFollower",
    "StepSequencer",
    "RandomSource",
    "ExpressionInput",
    "MIDISource",
    "EmotionSource",
    "create_preset_from_emotion",
    "get_effect_suggestions",
    "EFFECT_CATEGORIES",
    "ALL_EFFECTS",
]

